AWSTemplateFormatVersion: "2010-09-09"
Description: IBM VPC Template
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
       - Key: Name
         Value: IBM-VPC

 IBMInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: IBM-IGW
        
 AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
         Ref: VPC
      InternetGatewayId:
         Ref: IBMInternetGateway
         
 IBMPUBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "eu-west-2a"
      MapPublicIpOnLaunch: 'true'
      Tags:
      - Key: Name
        Value: IBM-PUB 
        
 IBMPVTSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "eu-west-2a"
      MapPublicIpOnLaunch: 'false'
      Tags:
      - Key: Name
        Value: IBM-PVT
        
 IBMPUBRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: VPC
      Tags:
      - Key: Name
        Value: IBM-PUB-RT       
